import Head from 'next/head';
import Image from 'next/image';
import { Header } from 'components';

export default function Home() {
  return (
    <>
      <Head>
        <title>Next.js by Vercel - The React Framework</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="h-[1200px]"></div>
    </>
  );
}
